WIP

diff --git a/tests/function_macros-10 b/tests/function_macros-10
--- a/tests/function_macros-10
+++ b/tests/function_macros-10
@@ -7,11 +7,12 @@
 : ${DMAKEPROG:=dmake}
 file1="mfile1.mk"
 tmpfiles="$file1"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-# Remove files from prior failed run
-rm -rf $tmpfiles
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 # Test 1 - Check that mktmp can write special characters into a file.
@@ -27,7 +28,7 @@ all :
 
 EOT
 
-output1=`eval ${DMAKEPROG} -r -f $file1`
+output1=`eval ../${DMAKEPROG} -r -f $file1`
 result1=$?
 comparewith=`printf "test1\n\ttest2\n    test3"`
 if test $result1 = 0 -a "$output1" = "$comparewith" ; then
@@ -51,7 +52,7 @@ all :
 
 EOT
 
-output2=`eval ${DMAKEPROG} -r -f $file1`
+output2=`eval ../${DMAKEPROG} -r -f $file1`
 result2=$?
 if test $result2 = 0 -a "$output2" = "text (to dump to file" ; then
   echo "Subtest 2: OK"
@@ -75,7 +76,7 @@ OBJ = fred.obj mary.obj
 	@cat \$(mktmp \$(OBJ:t"+\n"))
 EOT
 
-output3=`eval OOODMAKEMODE=y ${DMAKEPROG} -r -f $file1`
+output3=`eval OOODMAKEMODE=y ../${DMAKEPROG} -r -f $file1`
 result3=$?
 comparewith=`printf "fred.obj+\nmary.obj"`
 if test $result3 = 0 -a "$output3" = "$comparewith" ; then
@@ -100,7 +101,7 @@ OBJ = fred.obj mary.obj joe.obj
 	@cat <+\$(OBJ)+>
 EOT
 
-output4=`eval ${DMAKEPROG} -r -f $file1`
+output4=`eval ../${DMAKEPROG} -r -f $file1`
 result4=$?
 if test $result4 = 0 -a "$output4" = "fred.obj mary.obj joe.obj" ; then
   echo "Subtest 4: OK"
@@ -114,7 +115,7 @@ fi
 
 if test $result1 -eq 0 -a $result2 -eq 0 \
     -a $result3 -eq 0 -a $result4 -eq 0  ; then
-    echo "Success - Cleaning up" && rm -f ${tmpfiles}
+    echo "Success - Cleaning up" && $CLEANUP
     exit
 else
     echo "Failure!"
diff --git a/tests/function_macros-5 b/tests/function_macros-5
--- a/tests/function_macros-5
+++ b/tests/function_macros-5
@@ -9,10 +9,12 @@
 file1="makefile.mk"
 file2="stdout.txt"
 tmpfiles="$file1 $file2"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-trap 'rm -rf $tmpfiles' 1 2 3 15 
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 cat > $file1 <<EOT
@@ -34,13 +36,15 @@ all2 :
 	@+echo "Z\$(DYNMAC)Z"
 EOT
 
-${DMAKEPROG} -P3 -r -f $file1
+# '-#d:F:L:t,50'
+# valgrind --read-var-info=yes --leak-check=full --show-reachable=yes -v
+../${DMAKEPROG} -P3 -r -f $file1
 result=$?
 if test "`cat $file2`" != "Y(shellpre) (shellpost)Y"; then
   echo "Wrong result: `cat $file2`, Y(shellpre) (shellpost)Y expected!"
   result=1
 fi
 
-test $result -eq 0 && echo "Success - Cleaning up" && rm -f ${tmpfiles}
+test $result -eq 0 && echo "Success - Cleaning up" && $CLEANUP
 test $result -ne 0 && echo "Failure!"
 exit $result
diff --git a/tests/function_macros-7 b/tests/function_macros-7
--- a/tests/function_macros-7
+++ b/tests/function_macros-7
@@ -7,10 +7,12 @@
 : ${DMAKEPROG:=dmake}
 file1="makefile.mk"
 tmpfiles="$file1"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-trap 'rm -rf $tmpfiles' 1 2 3 15 
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 cat > $file1 <<EOT
@@ -23,7 +25,7 @@ all :
 
 EOT
 
-output1=`eval ${DMAKEPROG} -rf $file1 2>&1 `
+output1=`eval ../${DMAKEPROG} -rf $file1 2>&1 `
 result1=$?
 
 if test $output1 = "WRITTENTODISK" ; then
@@ -34,6 +36,6 @@ else
   result1=1
 fi
 
-test $result1 -eq 0 && echo "Success - Cleaning up" && rm -f ${tmpfiles}
+test $result1 -eq 0 && echo "Success - Cleaning up" && $CLEANUP
 test $result1 -ne 0 && echo "Failure!"
 exit $result1
diff --git a/tests/function_macros-8 b/tests/function_macros-8
--- a/tests/function_macros-8
+++ b/tests/function_macros-8
@@ -7,11 +7,12 @@
 : ${DMAKEPROG:=dmake}
 file1="mfile1.mk"
 tmpfiles="$file1"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-# Remove files from prior failed run
-rm -rf $tmpfiles
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 # Test 1 - Test if normpath works.
@@ -25,7 +26,7 @@ all :
 	@echo 1\$(normpath /tmp/./a "/tmp/a b/xxx/../b" /tmp)1
 EOT
 
-output1=`eval ${DMAKEPROG} -r -f $file1`
+output1=`eval ../${DMAKEPROG} -r -f $file1`
 result1=$?
 if test "$output1" != "1/tmp/a \"/tmp/a b/b\" /tmp1"; then
   echo "Subtest 1: Wrong result: $output1"
@@ -44,7 +45,7 @@ all .WINPATH :
 
 EOT
 
-output2=`eval ${DMAKEPROG} -r -f $file1`
+output2=`eval ../${DMAKEPROG} -r -f $file1`
 result2=$?
 if test x`uname -o 2> /dev/null` = "xCygwin"; then
   if test "$output2" != "2`cygpath -m /tmp`2"; then
@@ -72,7 +73,7 @@ all :
 
 EOT
 
-output3=`eval ${DMAKEPROG} -r -f $file1`
+output3=`eval ../${DMAKEPROG} -r -f $file1`
 result3=$?
 if test x`uname -o 2> /dev/null` = "xCygwin"; then
   if test "$output3" != "3/tmp3`cygpath -m /tmp`3"; then
@@ -93,7 +94,7 @@ fi
 
 if test $result1 -eq 0 -a $result2 -eq 0 \
     -a $result3 -eq 0 ; then
-    echo "Success - Cleaning up" && rm -f ${tmpfiles}
+    echo "Success - Cleaning up" && $CLEANUP
     exit
 else
     echo "Failure!"
diff --git a/tests/function_macros-9 b/tests/function_macros-9
--- a/tests/function_macros-9
+++ b/tests/function_macros-9
@@ -7,11 +7,12 @@
 : ${DMAKEPROG:=dmake}
 file1="mfile1.mk"
 tmpfiles="$file1"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-# Remove files from prior failed run
-rm -rf $tmpfiles
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 # Test 1 - Test if it works.
@@ -26,7 +27,7 @@ all :
 	noop X\$(shell,expand +@printf "\x24(AAA)")Y\$(shell +@printf \\\\x24\\(AAA\\))Z
 EOT
 
-output1=`eval ${DMAKEPROG} -r -f $file1`
+output1=`eval ../${DMAKEPROG} -r -f $file1`
 result1=$?
 if test "$output1" != "noop X123Y\$(AAA)Z"; then
   echo "Subtest 1: Wrong result: $output1"
@@ -48,7 +49,7 @@ all :
 
 EOT
 
-output2=`eval ${DMAKEPROG} -rf $file1 2>&1`
+output2=`eval ../${DMAKEPROG} -rf $file1 2>&1`
 result2=$?
 
 if echo $output2 | grep 'Error: -- Unknown argument \[XXX\] to shell' > /dev/null 2>&1 ; then
@@ -62,7 +63,7 @@ fi
 
 
 if test $result1 -eq 0 -a $result2 -ne 0 ; then
-    echo "Success - Cleaning up" && rm -f ${tmpfiles}
+    echo "Success - Cleaning up" && $CLEANUP
     exit
 else
     echo "Failure!"
diff --git a/tests/macros-2 b/tests/macros-2
--- a/tests/macros-2
+++ b/tests/macros-2
@@ -8,11 +8,12 @@ file1="mfile1.mk"
 file2="mfile2.mk"
 file3="dirwith space"
 tmpfiles="$file1 $file2"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles "$file3"; }' 1 2 3 15
-
-# Remove files from prior failed run
-rm -rf $tmpfiles "$file3"
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 # Testcase 1
@@ -36,9 +37,9 @@ all ".SETDIR=dirwith space" :
 	+@echo \$(TMD)
 EOT
 
-output1=`eval ${DMAKEPROG} -r -f $file1`
+output1=`eval ../${DMAKEPROG} -r -f $file1`
 result1=$?
-output2=`eval ${DMAKEPROG} -r -f $file2`
+output2=`eval ../${DMAKEPROG} -r -f $file2`
 result2=$?
 
 if test "$output1" = ""; then
@@ -52,7 +53,7 @@ fi
 
 if test $result1 -eq 0 -a $result2 -eq 0; then
   echo "Success - Cleaning up"
-  rm -rf $tmpfiles "$file3"
+  $CLEANUP
 exit
   result=0
 else
diff --git a/tests/macros-3 b/tests/macros-3
--- a/tests/macros-3
+++ b/tests/macros-3
@@ -9,11 +9,12 @@
 file1="mfile1.mk"
 file2="mfile2.mk"
 tmpfiles="$file1 $file2"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-# Remove files from prior failed run
-rm -rf $tmpfiles
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 # Testcase 1 - No warning expected
@@ -45,9 +46,9 @@ something :
 
 EOT
 
-output1=`eval ${DMAKEPROG} -r -f $file1 2>&1 `
+output1=`eval ../${DMAKEPROG} -r -f $file1 2>&1 `
 result1=$?
-output2=`eval ${DMAKEPROG} -r -f $file2 2>&1 `
+output2=`eval ../${DMAKEPROG} -r -f $file2 2>&1 `
 result2=$?
 
 if test "$output1" != "all"; then
@@ -61,7 +62,7 @@ fi
 
 if test $result1 -eq 0 -a $result2 -eq 0; then
   echo "Success - Cleaning up"
-  rm -rf $tmpfiles
+  $CLEANUP
 exit
   result=0
 else
diff --git a/tests/macros-4 b/tests/macros-4
--- a/tests/macros-4
+++ b/tests/macros-4
@@ -10,11 +10,12 @@ file2="mfile2.mk"
 file3="mfile3.mk"
 file4="mfile4.mk"
 tmpfiles="$file1 $file2 $file3 $file4"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-# Remove files from prior failed run
-rm -rf $tmpfiles
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 # Testcase 1 - Warn about miising closing braket.
@@ -54,13 +55,13 @@ all :
 	+@echo "X\$XX:Y"
 EOT
 
-output1=`eval ${DMAKEPROG} -r -f $file1 2>&1 `
+output1=`eval ../${DMAKEPROG} -r -f $file1 2>&1 `
 result1=$?
-output2=`eval ${DMAKEPROG} -r -f $file2 2>&1 `
+output2=`eval ../${DMAKEPROG} -r -f $file2 2>&1 `
 result2=$?
-output3=`eval ${DMAKEPROG} -r -f $file3 2>&1 `
+output3=`eval ../${DMAKEPROG} -r -f $file3 2>&1 `
 result3=$?
-output4=`eval ${DMAKEPROG} -r -f $file4 2>&1 `
+output4=`eval ../${DMAKEPROG} -r -f $file4 2>&1 `
 result4=$?
 
 if echo $output1 | grep -v 'Error: -- Syntax error'; then
@@ -82,7 +83,7 @@ fi
 
 if test $result1 -ne 0 -a $result2 -ne 0 -a $result3 -ne 0 -a $result4 -eq 0; then
   echo "Success - Cleaning up"
-  rm -rf $tmpfiles
+  $CLEANUP
 exit
   result=0
 else
diff --git a/tests/misc-13 b/tests/misc-13
--- a/tests/misc-13
+++ b/tests/misc-13
@@ -8,11 +8,12 @@
 file1="mfile1.mk"
 file2="TeSt.target"
 tmpfiles="$file1 $file2"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-# Remove files from prior failed run
-rm -rf $tmpfiles
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 echo "Something" > $file2
 
@@ -38,14 +39,18 @@ TeSt.target :
 
 EOT
 
-output=`eval ${DMAKEPROG} -vm -r -f $file1`
+output=`eval ../${DMAKEPROG} -vm -r -f $file1`
 result=$?
 
-if echo "$output" | grep -v ".target' is up to date"  > /dev/null 2>&1 ; then
+if echo "$output" | grep ".target' is up to date"  > /dev/null 2>&1
+then
+  # no-op, fine
+  :
+else
   echo "Wrong result: ${output}"
   result=1
 fi 
  
-test $result -eq 0 && echo "Success - Cleaning up" && rm -f ${tmpfiles}
+test $result -eq 0 && echo "Success - Cleaning up" && $CLEANUP
 test $result -ne 0 && echo "Failure!"
 exit $result
diff --git a/tests/misc-18 b/tests/misc-18
--- a/tests/misc-18
+++ b/tests/misc-18
@@ -8,11 +8,12 @@
 : ${DMAKEPROG:=dmake}
 file1="mfile1.mk"
 tmpfiles="$file1"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-# Remove files from prior failed run
-rm -rf $tmpfiles
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 # Test 1 - Test if .WINPATH is accepted as global attribute
@@ -27,7 +28,7 @@ all :
 
 EOT
 
-output1=`eval ${DMAKEPROG} -r -f $file1`
+output1=`eval ../${DMAKEPROG} -r -f $file1`
 result1=$?
 if test "$output1" != "OK1"; then
   echo "Subtest 1: Wrong result: $output1"
@@ -46,7 +47,7 @@ all .WINPATH :
 
 EOT
 
-output2=`eval ${DMAKEPROG} -r -f $file1`
+output2=`eval ../${DMAKEPROG} -r -f $file1`
 result2=$?
 if test "$output2" != "OK2"; then
   echo "Subtest 2: Wrong result: $output2"
@@ -67,7 +68,7 @@ SHELLFLAGS*:=-ce
 EOT
 
 if test x`uname -o 2> /dev/null` = "xCygwin"; then
-    output3=`eval ${DMAKEPROG} -r -f $file1`
+    output3=`eval ../${DMAKEPROG} -r -f $file1`
     result3=$?
     if test "$output3" != "at:`cygpath -m /tmp/blah.xx`:star:`cygpath -m /tmp/blah`:"; then
         echo "Subtest : Wrong result: $output3"
@@ -92,7 +93,7 @@ all .WINPATH .SETDIR=/tmp :
 EOT
 
 if test x`uname -o 2> /dev/null` = "xCygwin"; then
-    output4=`eval ${DMAKEPROG} -r -f $file1`
+    output4=`eval ../${DMAKEPROG} -r -f $file1`
     result4=$?
     mypwd=`pwd`
     if test "$output4" != ":`cygpath -m /tmp`:`cygpath -m $mypwd`:"; then
@@ -118,7 +119,7 @@ all .WINPATH .SETDIR=/ :
 EOT
 
 if test x`uname -o 2> /dev/null` = "xCygwin"; then
-    output5=`eval ${DMAKEPROG} -r -f $file1`
+    output5=`eval ../${DMAKEPROG} -r -f $file1`
     result5=$?
     mypwd=`pwd`
     if test "$output5" != ":`cygpath -m /`:`cygpath -m $mypwd`:"; then
@@ -144,7 +145,7 @@ SHELLFLAGS*:=-ce
 EOT
 
 if test x`uname -o 2> /dev/null` = "xCygwin"; then
-    output6=`eval ${DMAKEPROG} -r -f $file1`
+    output6=`eval ../${DMAKEPROG} -r -f $file1`
     result6=$?
     if test "$output6" != ":`cygpath -m /tmp/all.bla`:"; then
         echo "Subtest : Wrong result: $output6"
@@ -161,7 +162,7 @@ fi
 if test $result1 -eq 0 -a $result2 -eq 0 \
     -a $result3 -eq 0 -a $result4 -eq 0 \
     -a $result5 -eq 0 -a $result6 -eq 0; then
-    echo "Success - Cleaning up" && rm -f ${tmpfiles}
+    echo "Success - Cleaning up" && $CLEANUP
     exit
 else
     echo "Failure!"
diff --git a/tests/misc-7 b/tests/misc-7
--- a/tests/misc-7
+++ b/tests/misc-7
@@ -8,11 +8,12 @@
 file1="mfile1.mk"
 file2="subdir"
 tmpfiles="$file1 $file2"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-# Remove files from prior failed run
-rm -rf $tmpfiles
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 cat > $file1 <<EOT
@@ -28,7 +29,7 @@ EOT
 
 mkdir -p "$file2"
 
-output1=`eval ${DMAKEPROG} -r -f $file1`
+output1=`eval ../${DMAKEPROG} -r -f $file1`
 result1=$?
 
 if test "$output1" != ":$file2:"; then
@@ -38,7 +39,7 @@ fi
 
 if test $result1 -eq 0; then
   echo "Success - Cleaning up"
-  rm -rf ${tmpfiles}
+  $CLEANUP
   result=0
 else
   echo "Failure!"
diff --git a/tests/recipes-4 b/tests/recipes-4
--- a/tests/recipes-4
+++ b/tests/recipes-4
@@ -7,10 +7,12 @@
 : ${DMAKEPROG:=dmake}
 file1="mymakefile.mk"
 tmpfiles="$file1"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-trap 'rm -rf $tmpfiles' 1 2 3 15 
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 cat > $file1 <<EOT
@@ -25,7 +27,7 @@ all :
 
 EOT
 
-output=`eval ${DMAKEPROG} -r -f $file1`
+output=`eval ../${DMAKEPROG} -r -f $file1`
 result=$?
 if test "$output" != "\"AB  CD\"XY"; then
   echo "Wrong result: $output"
@@ -33,6 +35,6 @@ if test "$output" != "\"AB  CD\"XY"; then
 fi
 
 
-test $result -eq 0 && echo "Success - Cleaning up" && rm -f ${tmpfiles}
+test $result -eq 0 && echo "Success - Cleaning up" && $CLEANUP
 test $result -ne 0 && echo "Failure!"
 exit $result
diff --git a/tests/recipes-5 b/tests/recipes-5
--- a/tests/recipes-5
+++ b/tests/recipes-5
@@ -8,10 +8,12 @@
 file1="mfile1.mk"
 file2="ofile1.out"
 tmpfiles="$file1 $file2"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-trap 'rm -rf $tmpfiles' 1 2 3 15 
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 cat > $file1 <<EOT
@@ -24,7 +26,7 @@ all :
 	@@+echo something
 EOT
 
-output1=`eval ${DMAKEPROG} -r -f $file1`
+output1=`eval ../${DMAKEPROG} -r -f $file1`
 result1=$?
 if test "$output1" != ""; then
   echo "Wrong result: $output1"
@@ -41,7 +43,7 @@ else
 fi
 
 # Test if -vr enables the output again
-output2=`eval ${DMAKEPROG} -vr -rf $file1`
+output2=`eval ../${DMAKEPROG} -vr -rf $file1`
 result2=$?
 if echo $output2 | grep -v 'echo someoutput > ofile1.out'; then
   echo "Missing output: echo someoutput > ofile1.out"
@@ -54,7 +56,7 @@ fi
 
 if test $result1 -eq 0 -a $result2 -eq 0; then
   echo "Success - Cleaning up"
-  rm -f ${tmpfiles}
+  $CLEANUP
   exit 0
 else
   echo "Failure!"
diff --git a/tests/targets-12 b/tests/targets-12
--- a/tests/targets-12
+++ b/tests/targets-12
@@ -7,11 +7,12 @@
 : ${DMAKEPROG:=dmake}
 file1="mfile1.mk"
 tmpfiles="$file1"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-# Remove files from prior failed run
-rm -rf $tmpfiles
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 # Check that we issue a warning.
@@ -24,7 +25,7 @@ SHELLFLAGS*:=-ce
 all: ; @echo OK
 EOT
 
-output1=`eval ${DMAKEPROG} -vw -rf $file1 2>&1 `
+output1=`eval ../${DMAKEPROG} -vw -rf $file1 2>&1 `
 result1=$?
 
 if echo $output1 | grep 'Warning: -- The .SUFFIXES' > /dev/null 2>&1 ; then
@@ -38,7 +39,7 @@ fi
  
 if test $result1 -eq 0 ; then
   echo "Success - Cleaning up"
-  rm -rf $tmpfiles
+  $CLEANUP
   result=0
 else
   echo "Failure! dmake failed to issue a warning."
diff --git a/tests/targets-17 b/tests/targets-17
--- a/tests/targets-17
+++ b/tests/targets-17
@@ -7,11 +7,12 @@
 : ${DMAKEPROG:=dmake}
 file1="mfile1.mk"
 tmpfiles="$file1"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-# Remove files from prior failed run
-rm -rf $tmpfiles
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 cat > $file1 <<EOT
@@ -24,15 +25,15 @@ all : \$\$(EMPTYPRQ)
 	echo all
 EOT
 
-output1=`eval ${DMAKEPROG} -rf $file1 2>&1 `
+output1=`eval ../${DMAKEPROG} -rf $file1 2>&1 `
 result1=$?
 
 
 if test $result1 -eq 0 ; then
   echo "Success - Cleaning up"
-  rm -rf $tmpfiles
+  $CLEANUP
 else
   echo "Failure! dmake reported:"
   echo "$output1"
 fi
-exit $result
+exit $result1
diff --git a/tests/targets-18 b/tests/targets-18
--- a/tests/targets-18
+++ b/tests/targets-18
@@ -7,11 +7,12 @@
 : ${DMAKEPROG:=dmake}
 file1="mfile1.mk"
 tmpfiles="$file1"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-# Remove files from prior failed run
-rm -rf $tmpfiles
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 cat > $file1 <<EOT
@@ -27,7 +28,7 @@ SHELLFLAGS*:=-ce
 EOT
 
 
-output1=`eval OOODMAKEMODE="" ${DMAKEPROG} -rf $file1 2>&1 `
+output1=`eval OOODMAKEMODE="" ../${DMAKEPROG} -rf $file1 2>&1 `
 result1=$?
 if test $result1 -ne 0 -o "$output1" != "XallY"; then
   echo "Test 1: Wrong result: $output1"
@@ -35,7 +36,7 @@ if test $result1 -ne 0 -o "$output1" != "XallY"; then
 fi
 
 
-output2=`eval OOODMAKEMODE=y ${DMAKEPROG} -rf $file1 2>&1 `
+output2=`eval OOODMAKEMODE=y ../${DMAKEPROG} -rf $file1 2>&1 `
 result2=$?
 if test $result2 -ne 0 -o "$output2" != "X./allY"; then
   echo "Test 2: Wrong result: $output2"
@@ -44,7 +45,7 @@ fi
 
 if test $result1 -eq 0 -a $result2 -eq 0; then
   echo "Success - Cleaning up"
-  rm -rf $tmpfiles
+  $CLEANUP
   exit 0
 else
   echo "Failure!"
diff --git a/tests/targets-19 b/tests/targets-19
--- a/tests/targets-19
+++ b/tests/targets-19
@@ -7,11 +7,12 @@
 : ${DMAKEPROG:=dmake}
 file1="mfile1.mk"
 tmpfiles="$file1"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-# Remove files from prior failed run
-rm -rf $tmpfiles
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 # Test 1 - Test if excess leading slashes get removed
@@ -24,7 +25,7 @@ SHELLFLAGS*:=-ce
 
 EOT
 
-output1=`eval ${DMAKEPROG} -rf $file1 2>&1 `
+output1=`eval ../${DMAKEPROG} -rf $file1 2>&1 `
 result1=$?
 if test "$output1" != "X/allY"; then
   echo "Subtest 1: Wrong result: $output1"
@@ -45,7 +46,7 @@ SHELLFLAGS*:=-ce
 EOT
 
 if test x`uname -o 2> /dev/null` = "xCygwin"; then
-    output2=`eval ${DMAKEPROG} -r -f $file1`
+    output2=`eval ../${DMAKEPROG} -r -f $file1`
     result2=$?
     if test "$output2" != "Xc:/allY"; then
         echo "Subtest 2: Wrong result: $output2"
@@ -60,7 +61,7 @@ fi
 
 
 if test $result1 -eq 0 -a $result2 -eq 0; then
-    echo "Success - Cleaning up" && rm -f ${tmpfiles}
+    echo "Success - Cleaning up" && $CLEANUP
     exit
 else
     echo "Failure!"
diff --git a/tests/targets-20 b/tests/targets-20
--- a/tests/targets-20
+++ b/tests/targets-20
@@ -14,11 +14,12 @@ file2="ptarget.a"
 file3="ptarget.b"
 file4="ptarget.c"
 tmpfiles="$file1 $file2 $file3 $file4"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-# Remove files from prior failed run
-rm -rf $tmpfiles
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Create test environment
 touch ptarget.c
@@ -45,7 +46,7 @@ all : ptarget.a
 
 EOT
 
-output1=`eval ${DMAKEPROG} -rf $file1 2>&1 `
+output1=`eval ../${DMAKEPROG} -rf $file1 2>&1 `
 result1=$?
 
 if test "$output1" != "OKdone"; then
@@ -57,7 +58,7 @@ fi
 
 if test $result1 -eq 0 ; then
   echo "Success - Cleaning up"
-  rm -rf $tmpfiles
+  $CLEANUP
   exit
 else
   echo "Failure!"
diff --git a/tests/targets-27 b/tests/targets-27
--- a/tests/targets-27
+++ b/tests/targets-27
@@ -11,11 +11,12 @@ file2="aa.x"
 file3="aa.y"
 file4="aa.z"
 tmpfiles="$file1 $file2 $file3 $file4"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-# Remove files from prior failed run
-rm -rf $tmpfiles
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 cat > $file1 <<EOT
@@ -39,7 +40,7 @@ touch aa.z; sleep 1; touch aa.y ; sleep 1 ;touch aa.x
 # that has been rebuild.
 sleep 1
 
-output1=`eval ${DMAKEPROG} -rf $file1 aa.x 2>&1 `
+output1=`eval ../${DMAKEPROG} -rf $file1 aa.x 2>&1 `
 result1=$?
 
 if test "$output1" != "Build aa.y and aa.x."; then
@@ -51,7 +52,7 @@ fi
 
 if test $result1 -eq 0 ; then
   echo "Success - Cleaning up"
-  rm -rf $tmpfiles
+  $CLEANUP
   exit
 else
   echo "Failure!"
diff --git a/tests/targets-29 b/tests/targets-29
--- a/tests/targets-29
+++ b/tests/targets-29
@@ -10,11 +10,12 @@ file2="aaa.aaa"
 file3="aaa.bbb"
 file4="aaa.ccc"
 tmpfiles="$file1 $file2 $file3 $file4"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-# Remove files from prior failed run
-rm -rf $tmpfiles
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 cat > $file1 <<EOT
@@ -38,7 +39,7 @@ all : aaa.aaa
 
 EOT
 
-output1=`eval ${DMAKEPROG} -P2 -rf $file1 2>&1`
+output1=`eval ../${DMAKEPROG} -P2 -rf $file1 2>&1`
 result1=$?
 
 if test $result1 -ne 0; then
@@ -51,7 +52,7 @@ fi
 
 if test $result1 -eq 0 ; then
   echo "Success - Cleaning up"
-  rm -rf $tmpfiles
+  $CLEANUP
   exit
 else
   echo "Failure!"
diff --git a/tests/targets-3 b/tests/targets-3
--- a/tests/targets-3
+++ b/tests/targets-3
@@ -7,16 +7,17 @@
 : ${DMAKEPROG:=dmake}
 file1="mfile1.mk"
 tmpfiles="$file1"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
-trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15
-
-# Remove files from prior failed run
-rm -rf $tmpfiles
+trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
 # Testcase 1 - Check that warning is issued if .<suffix> targets are ignored
 cat > $file1 <<EOT
-SHELL*:=/bin/sh 
+SHELL*:=/bin/sh
 SHELLFLAGS*:=-ce
 
 .nada : something
@@ -26,7 +27,7 @@ something :
 
 EOT
 
-output1=`eval ${DMAKEPROG} -r -f $file1 2>&1 `
+output1=`eval ../${DMAKEPROG} -r -f $file1 2>&1 `
 result1=$?
 
 if echo $output1 | grep 'Warning: -- Ignoring AUGMAKE meta-target' > /dev/null 2>&1 ; then
@@ -39,7 +40,7 @@ fi
 
 if test $result1 -eq 0 ; then
   echo "Success - Cleaning up"
-  rm -rf $tmpfiles
+  $CLEANUP
 exit
   result=0
 else
